[package]
name = "bore"
version = "0.1.0"
authors = ["Lily Chung <lkdc@mit.edu>"]
edition = "2021"

[dependencies]
clap = "2.33.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sodiumoxide = "0.2.4"
tempfile = "3.1.0"
thiserror = "1.0"
